version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  langflow-app:
    build:
      context: .
      dockerfile: Dockerfile.backend  # or Dockerfile.backend, match your file name
    image: langflow-app
    container_name: langflow-app
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=adminpassword123
      - LANGFLOW_SECRET_KEY=23648756921
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
      - LANGFLOW_WORKER_TIMEOUT=60000
      - LANGFLOW_COMPONENTS_PATH=/app/custom_components
    volumes:
      - ./custom_components:/app/custom_components
    depends_on:
      - postgres

volumes:
  langflow-postgres:
