services:
  langflow-app:
    build:
      context: .
      dockerfile: docker/build_and_push_with_extras.Dockerfile
    image: langflow-app
    container_name: langflow-app
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_SUPERUSER=admin
      - LANGFLOW_SUPERUSER_PASSWORD=adminpassword
      - LANGFLOW_SECRET_KEY=23648756921
      - LANGFLOW_AUTO_LOGIN=false
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
      - LANGFLOW_COMPONENTS_PATH=/app/custom_components
    volumes:
      - ./data:/app/data
      - ./custom_components:/app/custom_components
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=langflow
      - POSTGRES_USER=langflow
      - POSTGRES_PASSWORD=langflow
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
